//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace Notification { namespace Dismisser {

ref class DismisserSignals;

public interface class IDismisserSignals
{
    event Windows::Foundation::TypedEventHandler<DismisserSignals^, DismisserDismissReceivedEventArgs^>^ DismissReceived;
};

public ref class DismisserSignals sealed : [Windows::Foundation::Metadata::Default] IDismisserSignals
{
public:
    // Calling this method will send the Dismiss signal to every member of the session.
    void Dismiss(_In_ int32 interfaceMemberArg, _In_ Windows::Foundation::Collections::IVectorView<byte>^ interfaceMemberArg2);

    // This event fires whenever the Dismiss signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<DismisserSignals^, DismisserDismissReceivedEventArgs^>^ DismissReceived 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<DismisserSignals^, DismisserDismissReceivedEventArgs^>^ handler) 
        { 
            return _DismissReceived += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<DismisserSignals^>(sender), safe_cast<DismisserDismissReceivedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _DismissReceived -= token; 
        } 
    internal: 
        void raise(DismisserSignals^ sender, DismisserDismissReceivedEventArgs^ args) 
        { 
            _DismissReceived(sender, args);
        } 
    }

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallDismissReceived(_In_ DismisserSignals^ sender, _In_ DismisserDismissReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _DismissReceived;

    alljoyn_interfacedescription_member m_memberDismiss;
};

} } } } 
