//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace Notification {

// Signals
public ref class NotificationNotifyReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property uint16 Arg
    {
        uint16 get() { return m_interfaceMemberArg; }
    internal:
        void set(_In_ uint16 value) { m_interfaceMemberArg = value; }
    }
    property int32 Arg2
    {
        int32 get() { return m_interfaceMemberArg2; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberArg2 = value; }
    }
    property uint16 Arg3
    {
        uint16 get() { return m_interfaceMemberArg3; }
    internal:
        void set(_In_ uint16 value) { m_interfaceMemberArg3 = value; }
    }
    property Platform::String^ Arg4
    {
        Platform::String^ get() { return m_interfaceMemberArg4; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberArg4 = value; }
    }
    property Platform::String^ Arg5
    {
        Platform::String^ get() { return m_interfaceMemberArg5; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberArg5 = value; }
    }
    property Windows::Foundation::Collections::IVector<byte>^ Arg6
    {
        Windows::Foundation::Collections::IVector<byte>^ get() { return m_interfaceMemberArg6; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IVector<byte>^ value) { m_interfaceMemberArg6 = value; }
    }
    property Platform::String^ Arg7
    {
        Platform::String^ get() { return m_interfaceMemberArg7; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberArg7 = value; }
    }
    property Windows::Foundation::Collections::IMap<int32,Platform::Object^>^ Arg8
    {
        Windows::Foundation::Collections::IMap<int32,Platform::Object^>^ get() { return m_interfaceMemberArg8; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IMap<int32,Platform::Object^>^ value) { m_interfaceMemberArg8 = value; }
    }
    property Windows::Foundation::Collections::IMap<Platform::String^,Platform::String^>^ Arg9
    {
        Windows::Foundation::Collections::IMap<Platform::String^,Platform::String^>^ get() { return m_interfaceMemberArg9; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IMap<Platform::String^,Platform::String^>^ value) { m_interfaceMemberArg9 = value; }
    }
    property Windows::Foundation::Collections::IVector<NotificationItem^>^ Arg10
    {
        Windows::Foundation::Collections::IVector<NotificationItem^>^ get() { return m_interfaceMemberArg10; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IVector<NotificationItem^>^ value) { m_interfaceMemberArg10 = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    uint16 m_interfaceMemberArg;
    int32 m_interfaceMemberArg2;
    uint16 m_interfaceMemberArg3;
    Platform::String^ m_interfaceMemberArg4;
    Platform::String^ m_interfaceMemberArg5;
    Windows::Foundation::Collections::IVector<byte>^ m_interfaceMemberArg6;
    Platform::String^ m_interfaceMemberArg7;
    Windows::Foundation::Collections::IMap<int32,Platform::Object^>^ m_interfaceMemberArg8;
    Windows::Foundation::Collections::IMap<Platform::String^,Platform::String^>^ m_interfaceMemberArg9;
    Windows::Foundation::Collections::IVector<NotificationItem^>^ m_interfaceMemberArg10;
};


} } } 
